CREATE TABLE IF NOT EXISTS demo_trades (
  id VARCHAR(36) PRIMARY KEY,
  deployment_id VARCHAR(36) REFERENCES deployments(id),
  strategy_id VARCHAR(96) NOT NULL,
  strategy_version VARCHAR(48) NOT NULL,
  config_checksum VARCHAR(64) NOT NULL,
  broker_symbol VARCHAR(64) NOT NULL,
  environment VARCHAR(16) NOT NULL,
  deal_ticket VARCHAR(32) NOT NULL UNIQUE,
  position_id VARCHAR(32),
  side VARCHAR(16) NOT NULL,
  entry_timestamp VARCHAR(64),
  entry_price DOUBLE PRECISION,
  exit_timestamp VARCHAR(64),
  exit_price DOUBLE PRECISION,
  stop_loss DOUBLE PRECISION,
  take_profit DOUBLE PRECISION,
  volume DOUBLE PRECISION,
  exit_reason VARCHAR(64),
  realized_pnl DOUBLE PRECISION,
  commission DOUBLE PRECISION,
  swap DOUBLE PRECISION,
  spread_price DOUBLE PRECISION,
  execution_state VARCHAR(48) NOT NULL,
  raw JSON NOT NULL,
  observed_at TIMESTAMP NOT NULL
);
