"use client";

import Link from "next/link";
import React, { useEffect, useMemo, useState } from "react";

type Strategy = { id: string; name: string; version: number; status: string; checksum: string };
type Broker = { id: string; fingerprint: string; broker_symbol: string; collected_at: string; metadata: { account_currency?: string; volume_min?: number; volume_max?: number; volume_step?: number; trade_calc_mode?: number } };
type Contract = { id: string; status: string; fingerprint: string; contract: { starting_capital: { amount: number; currency: string }; sizing_policy: { mode: string; fixed_volume?: number; risk_fraction?: number; compounding: boolean }; margin_policy: { max_margin_fraction: number } }; broker_assessment: { status: string }; reused?: boolean };
type FullValidation = { id: string; status: string; fingerprint: string; result: { metrics?: { trade_count?: number; net_pnl_price?: number } } };
type Metrics = { source_trades_observed: number; executed_trades: number; rejected_trades: number; rejections_by_reason: Record<string, number>; starting_capital: number; ending_balance: number; net_pnl: number; maximum_drawdown: number; capital_path_points: number };
type Simulation = { id: string; status: string; fingerprint: string; reused?: boolean; capital_path_points: number; result: { metrics: Metrics; lineage: Record<string, unknown>; boundaries: Record<string, boolean>; warning: string } };
export type Verification = { status: "PASSED" | "FAILED"; owner_acceptance_readiness: "READY_FOR_OWNER_ACCEPTANCE" | "NOT_READY_FOR_OWNER_ACCEPTANCE"; checks: Record<string, { status: "PASS" | "FAIL"; observed?: unknown; expected?: unknown }>; warning: string; reused?: boolean };
type PathResponse = { total: number; capital_path: Array<Record<string, unknown>> };
type Form = { startingCapital: number; mode: "FIXED_LOT" | "FRACTIONAL_RISK"; fixedVolume: number; riskPercent: number; compounding: boolean; leverage: number; marginPercent: number };

const initialForm: Form = { startingCapital: 10000, mode: "FIXED_LOT", fixedVolume: 0.01, riskPercent: 1, compounding: false, leverage: 500, marginPercent: 80 };
const labels: Record<string, string> = { completed_result: "Simulation completed", source_trade_invariant: "Every canonical source trade accounted for", normalized_point_count: "Normalized capital-path count", contiguous_sequence: "Contiguous sequence", exact_path_payloads: "Every payload matches its canonical source trade", exact_lineage: "Exact immutable lineage", broker_parity: "MT5 profit and margin parity", constraint_boundaries: "Volume, margin, and unable-to-trade constraints", frozen_snapshot_disclosure: "Frozen broker-snapshot disclosure", lifecycle_safety: "No validation or deployment side effect" };
const requiredChecks = Object.keys(labels).sort();

function detail(value: unknown) { return typeof value === "object" && value && "detail" in value ? String((value as { detail: unknown }).detail) : "Request could not be completed."; }
async function read(response: Response) { const body = await response.json(); if (!response.ok) throw Error(detail(body)); return body; }
export function isAcceptanceReady(value: Verification | null) { return !!value && value.status === "PASSED" && value.owner_acceptance_readiness === "READY_FOR_OWNER_ACCEPTANCE" && JSON.stringify(Object.keys(value.checks).sort()) === JSON.stringify(requiredChecks) && Object.values(value.checks).every(check => check.status === "PASS"); }

export function CapitalSimulationEvidence({ simulation, verification, path }: { simulation: Simulation; verification: Verification; path: PathResponse | null }) {
  const metrics = simulation.result.metrics; const ready = isAcceptanceReady(verification);
  return <section className="panel result-panel capital-evidence" aria-label="Owner capital simulation evidence"><div className="panel-header"><div><p className="discovery-kicker">FULL-HISTORY BROKER-CONSTRAINED EVIDENCE</p><h2>{ready ? "Ready for Owner acceptance" : "Not ready for acceptance"}</h2><p>Simulation {simulation.id.slice(0, 8)} · fingerprint {simulation.fingerprint.slice(0, 16)}{simulation.reused ? " · reused" : ""}</p></div><span className={`capital-readiness ${ready ? "passed" : "failed"}`}>{verification.owner_acceptance_readiness}</span></div>
    <section className="command-metrics"><article><small>Starting capital</small><strong>{metrics.starting_capital}</strong></article><article><small>Ending balance</small><strong>{metrics.ending_balance}</strong></article><article><small>Net PnL</small><strong>{metrics.net_pnl}</strong></article><article><small>Maximum drawdown</small><strong>{metrics.maximum_drawdown}</strong></article><article><small>Source trades</small><strong>{metrics.source_trades_observed}</strong></article><article><small>Executed</small><strong>{metrics.executed_trades}</strong></article><article><small>Rejected</small><strong>{metrics.rejected_trades}</strong></article><article><small>Path points</small><strong>{metrics.capital_path_points}</strong></article></section>
    <div className="capital-result-grid"><section><h3>Acceptance checklist</h3><div className="capital-checks">{Object.entries(verification.checks).map(([key, check]) => <article key={key}><span className={`validation-status ${check.status === "PASS" ? "passed" : "failed"}`}>{check.status}</span><div><strong>{labels[key] ?? key}</strong><small>{JSON.stringify(check.observed ?? "Recorded")}</small></div></article>)}</div></section><section><h3>Rejected trade reasons</h3><div className="capital-rejections">{Object.entries(metrics.rejections_by_reason).length ? Object.entries(metrics.rejections_by_reason).map(([reason, count]) => <p key={reason}><span>{reason}</span><strong>{count}</strong></p>) : <p><span>No rejected trades</span><strong>0</strong></p>}</div><h3>Capital-path boundary sample</h3><pre>{path ? JSON.stringify(path.capital_path, null, 2) : "Open evidence to load first and last points."}</pre></section></div>
    <p className="warning-line">{simulation.result.warning}</p><p className="warning-line"><strong>Acceptance readiness is integrity evidence only.</strong> It is not VALIDATED, DEMO/LIVE authorization, or a trade recommendation.</p><details className="discovery-advanced"><summary>Immutable lineage and boundaries</summary><pre>{JSON.stringify({ lineage: simulation.result.lineage, boundaries: simulation.result.boundaries }, null, 2)}</pre></details></section>;
}

export function CapitalSimulationLab() {
  const [strategies, setStrategies] = useState<Strategy[]>([]); const [strategyId, setStrategyId] = useState(""); const [broker, setBroker] = useState<Broker | null>(null); const [form, setForm] = useState(initialForm);
  const [validation, setValidation] = useState<{ broker_assessment: { ready: boolean; status: string; issues: string[] }; contract: unknown } | null>(null); const [contracts, setContracts] = useState<Contract[]>([]); const [contractId, setContractId] = useState("");
  const [validations, setValidations] = useState<FullValidation[]>([]); const [fullId, setFullId] = useState(""); const [simulations, setSimulations] = useState<Simulation[]>([]); const [evidence, setEvidence] = useState<Simulation | null>(null); const [verification, setVerification] = useState<Verification | null>(null); const [path, setPath] = useState<PathResponse | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const contractPayload = useMemo(() => ({ schema_version: 1, starting_capital: { amount: form.startingCapital, currency: broker?.metadata.account_currency ?? "USD" }, sizing_policy: form.mode === "FIXED_LOT" ? { mode: form.mode, fixed_volume: form.fixedVolume, compounding: false } : { mode: form.mode, risk_fraction: form.riskPercent / 100, compounding: form.compounding }, account_assumptions: { leverage: form.leverage, leverage_source: "OWNER_INPUT" }, margin_policy: { max_margin_fraction: form.marginPercent / 100, insufficient_margin_action: "REJECT_TRADE" }, failure_policy: { invalid_volume: "REJECT_TRADE", missing_broker_metadata: "BLOCK_SIMULATION", unverified_profit_conversion: "BLOCK_SIMULATION" } }), [broker, form]);
  const post = async (url: string, body: unknown) => read(await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }));
  useEffect(() => { void (async () => { try { const [s, b] = await Promise.all([fetch("/api/v1/strategy-versions", { cache: "no-store" }).then(read), fetch("/api/v1/broker-metadata/latest", { cache: "no-store" }).then(read)]); const eligible = (s.strategy_versions ?? []).filter((item: Strategy) => ["CONTRACT_VALID", "VALIDATED"].includes(item.status)); setStrategies(eligible); setStrategyId(eligible[0]?.id ?? ""); setBroker(b); } catch (error) { setMessage(error instanceof Error ? error.message : "Initial evidence could not be loaded."); } })(); }, []);
  useEffect(() => { setValidation(null); setContractId(""); setFullId(""); setEvidence(null); setVerification(null); setPath(null); if (!strategyId) return; void Promise.all([fetch(`/api/v1/strategy-versions/${strategyId}/capital-contracts`, { cache: "no-store" }).then(read), fetch(`/api/v1/strategy-versions/${strategyId}/supplemental-historical-validations`, { cache: "no-store" }).then(read)]).then(([c, v]) => { const nextContracts = c.capital_contracts ?? []; const nextValidations = (v.validations ?? []).filter((item: FullValidation) => item.status === "COMPLETED"); setContracts(nextContracts); setContractId(nextContracts[0]?.id ?? ""); setValidations(nextValidations); setFullId(nextValidations[0]?.id ?? ""); }).catch(error => setMessage(error.message)); }, [strategyId]);
  useEffect(() => { setSimulations([]); if (!contractId) return; void fetch(`/api/v1/capital-contracts/${contractId}/constrained-simulations`, { cache: "no-store" }).then(read).then(body => setSimulations(body.simulations ?? [])).catch(error => setMessage(error.message)); }, [contractId]);
  async function act(task: () => Promise<void>) { setBusy(true); setMessage(""); try { await task(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed."); } finally { setBusy(false); } }
  const validate = () => act(async () => { if (!broker || !strategyId) throw Error("Select a StrategyVersion and broker snapshot."); const report = await post("/api/v1/capital-contracts/validate", { strategy_version_id: strategyId, broker_metadata_snapshot_id: broker.id, contract: contractPayload }); setValidation(report); setMessage(report.broker_assessment.ready ? "Contract is ready to be confirmed." : report.broker_assessment.issues.join(" ")); });
  const confirm = () => act(async () => { if (!broker || !strategyId || !validation?.broker_assessment.ready) throw Error("Validate a ready contract first."); const item = await post(`/api/v1/strategy-versions/${strategyId}/capital-contracts`, { broker_metadata_snapshot_id: broker.id, contract: contractPayload }) as Contract; setContracts(current => [item, ...current.filter(value => value.id !== item.id)]); setContractId(item.id); setMessage(item.reused ? "Identical immutable contract reused." : "Immutable capital contract confirmed."); });
  const open = (item: Simulation) => act(async () => { const [full, check] = await Promise.all([fetch(`/api/v1/constrained-capital-simulations/${item.id}`, { cache: "no-store" }).then(read), fetch(`/api/v1/constrained-capital-simulations/${item.id}/verification`, { method: "POST", cache: "no-store" }).then(read)]); const total = full.capital_path_points as number; const [first, last] = await Promise.all([fetch(`/api/v1/constrained-capital-simulations/${item.id}/capital-path?offset=0&limit=2`, { cache: "no-store" }).then(read), fetch(`/api/v1/constrained-capital-simulations/${item.id}/capital-path?offset=${Math.max(0, total - 2)}&limit=2`, { cache: "no-store" }).then(read)]); setEvidence(full); setVerification(check); setPath({ total, capital_path: [...first.capital_path, ...last.capital_path] }); setMessage(isAcceptanceReady(check) ? `Full-history integrity verification PASSED${check.reused ? " · immutable artifact reused" : ""}.` : "Verification found a blocking check."); });
  const run = () => act(async () => { if (!contractId || !fullId) throw Error("Select a contract and completed full-history source."); const item = await post(`/api/v1/capital-contracts/${contractId}/constrained-simulations`, { source_full_validation_id: fullId }) as Simulation; setSimulations(current => [item, ...current.filter(value => value.id !== item.id)]); setMessage(item.reused ? "Identical constrained simulation reused; open it to verify." : "Constrained simulation completed; open it to verify."); });
  const update = <K extends keyof Form>(key: K, value: Form[K]) => { setForm(current => ({ ...current, [key]: value })); setValidation(null); };
  return <main className="backtest-page"><header><div><Link className="back-link" href="/strategies">← Strategy Library</Link><h1>Capital Simulation</h1><p>Owner-controlled, immutable broker-constrained full-history evidence.</p></div><span className="mode-badge">HISTORICAL ONLY · LIVE LOCKED</span></header><section className="backtest-content">{message && <p className="notice">{message}</p>}
    <section className="capital-grid"><section className="panel backtest-config capital-panel"><p className="discovery-kicker">1 · IMMUTABLE CONTRACT</p><h2>Capital and sizing assumptions</h2><label className="deploy-label">StrategyVersion<select value={strategyId} onChange={event => setStrategyId(event.target.value)}><option value="">Choose an eligible version</option>{strategies.map(item => <option key={item.id} value={item.id}>{item.name} · v{item.version} · {item.status}</option>)}</select></label><label className="deploy-label">Sizing mode<select value={form.mode} onChange={event => update("mode", event.target.value as Form["mode"])}><option>FIXED_LOT</option><option>FRACTIONAL_RISK</option></select></label><div className="backtest-form"><label>Starting capital<input type="number" value={form.startingCapital} onChange={event => update("startingCapital", event.target.valueAsNumber)} /></label>{form.mode === "FIXED_LOT" ? <label>Fixed volume<input type="number" step="0.01" value={form.fixedVolume} onChange={event => update("fixedVolume", event.target.valueAsNumber)} /></label> : <><label>Risk percent<input type="number" step="0.1" value={form.riskPercent} onChange={event => update("riskPercent", event.target.valueAsNumber)} /></label><label>Compounding<select value={String(form.compounding)} onChange={event => update("compounding", event.target.value === "true")}><option value="false">No</option><option value="true">Yes</option></select></label></>}<label>Owner leverage<input type="number" value={form.leverage} onChange={event => update("leverage", event.target.valueAsNumber)} /></label><label>Margin ceiling %<input type="number" value={form.marginPercent} onChange={event => update("marginPercent", event.target.valueAsNumber)} /></label></div><p className="capital-snapshot">Latest MT5 snapshot: <strong>{broker ? `${broker.broker_symbol} · ${broker.collected_at}` : "loading"}</strong></p><div className="actions"><button className="secondary" disabled={busy} onClick={validate}>Validate</button><button className="run-button" disabled={busy || validation?.broker_assessment.ready !== true} onClick={confirm}>Confirm immutable contract</button></div>{validation && <div className={`factory-state ${validation.broker_assessment.ready ? "ready" : "invalid"}`}><strong>{validation.broker_assessment.status}</strong><span>{validation.broker_assessment.issues.join(" ") || "All frozen contract checks passed."}</span></div>}</section>
      <section className="panel backtest-config capital-panel"><p className="discovery-kicker">2 · EXACT LINEAGE</p><h2>Select recorded evidence</h2><label className="deploy-label">Capital contract<select value={contractId} onChange={event => setContractId(event.target.value)}><option value="">Choose confirmed contract</option>{contracts.map(item => <option key={item.id} value={item.id}>{item.contract.sizing_policy.mode} · {item.fingerprint.slice(0, 12)}</option>)}</select></label><label className="deploy-label">Completed full-history validation<select value={fullId} onChange={event => setFullId(event.target.value)}><option value="">Choose exact source</option>{validations.map(item => <option key={item.id} value={item.id}>{item.result.metrics?.trade_count ?? "?"} trades · {item.fingerprint.slice(0, 12)}</option>)}</select></label><button className="run-button" disabled={busy || !contractId || !fullId} onClick={run}>Run / reuse constrained simulation</button><p className="muted">The canonical kernel is traversed once. Source evidence is never rewritten.</p></section>
      <section className="panel backtest-info capital-panel"><p className="discovery-kicker">SAFETY BOUNDARY</p><h2>What acceptance means</h2><p>The verifier checks full normalized point coverage, exact lineage, MT5 parity, broker constraints, frozen-snapshot disclosure, and lifecycle safety.</p><p><strong>READY_FOR_OWNER_ACCEPTANCE does not claim VALIDATED.</strong> It cannot deploy, route orders, or authorize DEMO/LIVE.</p><p>One current broker snapshot is frozen across the historical period; historical broker-term changes are not reconstructed.</p></section></section>
    <section className="panel result-panel"><div className="panel-header"><div><h2>Recorded constrained simulations</h2><p>Open a result to materialize once or reuse its immutable full-replay acceptance artifact.</p></div></div>{simulations.length ? <div className="strategy-list">{simulations.map(item => <article className="strategy-card" key={item.id}><div><small>{item.status}</small><h2>{item.id.slice(0, 8)}</h2><p>Fingerprint {item.fingerprint.slice(0, 16)} · {item.capital_path_points} normalized points</p></div><button className="secondary" disabled={busy} onClick={() => open(item)}>Open and verify</button></article>)}</div> : <p className="empty-library muted">No constrained simulation recorded for this contract.</p>}</section>
    {evidence && verification && <CapitalSimulationEvidence simulation={evidence} verification={verification} path={path} />}</section></main>;
}
