import { renderToStaticMarkup } from "react-dom/server";
import React from "react";
import { expect, test } from "vitest";
import { CurrentDecisionView, RouterDecision, RouterParameters, RouterVerification } from "./current-decision";
const decision:RouterDecision={id:"decision-1",selected_strategy_version_id:null,evaluated_at:"2026-08-25T10:00:00Z",fingerprint:"d".repeat(64),decision:"NO_TRADE",reason_codes:["ELIGIBILITY_INELIGIBLE"],selected:null,candidates:[],decision_semantics:{least_bad_fallback:false},safety_boundary:{order_or_trade_created:false}};
const parameters:RouterParameters={id:"parameters-1",status:"NO_TRADE",fingerprint:"p".repeat(64),broker_metadata_snapshot_id:null,capital_contract_id:null,parameters:null,lineage:{decision:{id:"decision-1"}},reason_codes:["ROUTER_DECISION_NO_TRADE"],safety_boundary:{order_or_trade_created:false}};
const verification:RouterVerification={id:"verification-1",status:"PASSED",owner_acceptance_readiness:"READY_FOR_OWNER_ACCEPTANCE",fingerprint:"v".repeat(64),router_outcome:"NO_TRADE",parameter_status:"NO_TRADE",checks:{decision_identity:{status:"PASS",observed:{decision:"NO_TRADE"}}},safety_boundary:{order_or_trade_created:false},warning:"Integrity only; no trading authority."};
test("renders honest NO_TRADE, null parameters, lineage and verifier",()=>{const html=renderToStaticMarkup(<CurrentDecisionView decision={decision} parameters={parameters} verification={verification} onVerify={()=>{}}/>);expect(html).toContain("No trade is permitted");expect(html).toContain("No Entry, SL, TP, or size exists");expect(html).toContain("ELIGIBILITY INELIGIBLE");expect(html).toContain("READY_FOR_OWNER_ACCEPTANCE");expect(html).toContain("cannot deploy, contact MT5, or place an order")});
test("renders exact LONG numbers without calling execution",()=>{const long={...decision,decision:"LONG" as const,selected_strategy_version_id:"strategy-1",reason_codes:[]};const ready={...parameters,status:"READY_FOR_OWNER_REVIEW",parameters:{side:"BUY",entry:104.02,stop_loss:103.92,take_profit:104.22,volume:.01,price_digits:2,tick_size:.01,calculation:{}}};const html=renderToStaticMarkup(<CurrentDecisionView decision={long} parameters={ready} verification={null} onVerify={()=>{}}/>);expect(html).toContain("104.02");expect(html).toContain("103.92");expect(html).toContain("104.22");expect(html).toContain("0.01")});
