"use client";
import React from "react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Strategy = { id: string; name: string; version: number; status: string };
// ARK-S24-07: evidence_grade is optional, so an older API response is still usable.
type Dataset = { id: string; fingerprint: string; symbol: string; timeframes: { timeframe: string; row_count: number }[]; evidence_grade?: boolean };
type Contract = { id: string; strategy_version_id: string; dataset_id: string; fingerprint: string; status: string; contract: { combination_count: number; axes: Record<string, number[]>; split_bounds: Record<string, { start: number; end: number }> }; assessment: unknown; reused?: boolean };
type Variant = { ordinal: number; fingerprint: string; parameters: Record<string, number>; baseline: boolean; comparison: { classification: string }; eligibility: { eligible: boolean }; scenarios: Record<string, { holdout: { metrics: Record<string, number | string | null> } }> };
type TrainRun = { id: string; fingerprint: string; status: string; result: { matrix?: { combination_count: number }; baseline_parity?: { status: string }; split_access?: Record<string, unknown> }; reused?: boolean };
export type HoldoutRun = { id: string; fingerprint: string; status: string; result: { matrix: { variants: Variant[] }; baseline_parity: { status: string }; split_access: Record<string, unknown> }; selection: { id: string; fingerprint: string; status: string; selected_variant_fingerprint: string | null; result: { eligible_count: number; ranked_eligible_variants: unknown[]; final_oos_accessed: boolean; locked: boolean } }; reused?: boolean };
type Check = { status: "PASS" | "FAIL"; observed?: unknown; expected?: unknown };
type ContractValidation = { assessment: { ready: boolean; status: string; issues: string[] } };
export type VariantVerification = { status: string; owner_acceptance_readiness: string; terminal_state: string; checks: Record<string, Check>; fingerprint: string; warning: string; reused?: boolean };

const requiredChecks = ["immutable_contract", "complete_train_matrix", "train_split_isolation", "complete_holdout_matrix", "holdout_final_oos_isolation", "comparison_eligibility_ranking", "immutable_selection_lock", "revision_oos_lineage", "single_winner_idempotency", "lifecycle_safety"];
export function isVariantAcceptanceReady(value: VariantVerification | null) { return Boolean(value && value.status === "PASSED" && value.owner_acceptance_readiness === "READY_FOR_OWNER_ACCEPTANCE" && requiredChecks.every(key => value.checks[key]?.status === "PASS")); }

const costScenarios = { baseline: { spread_multiplier: 1, commission_multiplier: 1 }, adverse_cost: { spread_multiplier: 1.5, commission_multiplier: 2 } };
const partitionPolicy = { protocol_version: "OOS_HISTORICAL_REVIEW_V3", partitioning: "CHRONOLOGICAL_COMPLETED_M1_BARS", splits: { train: .6, holdout: .2, final_oos: .2 }, boundary_semantics: "ISOLATED_KERNEL_STATE_PER_SPLIT", access_sequence: ["TRAIN_SCREEN", "HOLDOUT_SELECT", "LOCK_SELECTION", "OWNER_CONFIRM", "FINAL_OOS"] };
const selectionPolicy = { eligibility: { minimum_holdout_trades: 100, require_positive_net_pnl: true, profit_factor_strictly_greater_than: 1.1, required_cost_scenarios: ["baseline", "adverse_cost"] }, ranking: ["HIGHEST_WORST_CASE_PROFIT_FACTOR", "HIGHEST_WORST_CASE_NET_PNL", "SMALLEST_MAX_DRAWDOWN_MAGNITUDE", "LOWEST_VARIANT_FINGERPRINT"], maximum_selected_variants: 1 };
const labels: Record<string, string> = { immutable_contract: "Immutable contract", complete_train_matrix: "Complete train matrix", train_split_isolation: "Train split isolation", complete_holdout_matrix: "Complete holdout matrix", holdout_final_oos_isolation: "Holdout / final-OOS isolation", comparison_eligibility_ranking: "Comparison, eligibility, ranking", immutable_selection_lock: "Immutable selection lock", revision_oos_lineage: "Revision / protocol-V3 lineage", single_winner_idempotency: "Single-winner idempotency", lifecycle_safety: "Lifecycle safety" };

async function read(response: Response) { const body = await response.json(); if (!response.ok) throw Error(body.detail ?? `Request failed (${response.status})`); return body; }
const post = (url: string, body?: unknown) => fetch(url, { method: "POST", headers: body === undefined ? undefined : { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body), cache: "no-store" }).then(read);
const axis = (value: string) => [...new Set(value.split(",").map(item => Number(item.trim())).filter(item => Number.isFinite(item) && item > 0))].sort((a, b) => a - b);

export function VariantEvidence({ train, holdout, verification, busy, onConfirm, onVerify }: { train: TrainRun | null; holdout: HoldoutRun; verification: VariantVerification | null; busy: boolean; onConfirm: () => void; onVerify: () => void }) {
  const noEligible = holdout.selection.status === "NO_ELIGIBLE_VARIANT";
  return <><section className="panel variant-terminal"><div><p className="discovery-kicker">LOCKED HISTORICAL RESULT</p><h2>{holdout.selection.status}</h2><p>{noEligible ? "No challenger passed the absolute nominal and adverse-cost gate. No revision or final-OOS action is permitted." : `Selected ${holdout.selection.selected_variant_fingerprint}`}</p></div><div className="actions"><button className="run-button" disabled={busy || noEligible} onClick={onConfirm}>{noEligible ? "Final-OOS blocked — no eligible variant" : "Confirm revision + final-OOS"}</button><button className="secondary" disabled={busy} onClick={onVerify}>Materialize acceptance verifier</button></div></section>
    <section className="panel result-panel"><div className="panel-header"><div><h2>Split-use ledger</h2><p>Final-OOS remains locked unless one eligible selection is explicitly confirmed.</p></div><span className="mode-badge">FINAL-OOS {holdout.selection.result.final_oos_accessed ? "ACCESSED" : "LOCKED"}</span></div><div className="variant-splits"><article><small>TRAIN</small><strong>{train?.result.baseline_parity?.status ?? "UNKNOWN"}</strong><pre>{JSON.stringify(train?.result.split_access ?? {}, null, 2)}</pre></article><article><small>HOLDOUT</small><strong>{holdout.result.baseline_parity.status}</strong><pre>{JSON.stringify(holdout.result.split_access, null, 2)}</pre></article><article><small>SELECTION</small><strong>{holdout.selection.status}</strong><p>{holdout.selection.result.eligible_count} eligible · lock {holdout.selection.fingerprint.slice(0, 14)}</p></article></div></section>
    <section className="panel result-panel"><div className="panel-header"><div><h2>Holdout marginal-value matrix</h2><p>Relative classification never overrides the absolute eligibility gate.</p></div></div><div className="variant-table"><table><thead><tr><th>#</th><th>SL / TP</th><th>Classification</th><th>Eligible</th><th>Nominal PnL / PF</th><th>Adverse PnL / PF</th><th>Fingerprint</th></tr></thead><tbody>{holdout.result.matrix.variants.map(item => { const nominal = item.scenarios.baseline.holdout.metrics; const adverse = item.scenarios.adverse_cost.holdout.metrics; return <tr key={item.fingerprint}><td>{item.ordinal}{item.baseline ? " · BASE" : ""}</td><td>{item.parameters["stop_loss_rule.distance"]} / {item.parameters["take_profit_rule.distance"]}</td><td>{item.comparison.classification}</td><td><span className={`validation-status ${item.eligibility.eligible ? "passed" : "failed"}`}>{item.eligibility.eligible ? "YES" : "NO"}</span></td><td>{String(nominal.net_pnl_price)} / {String(nominal.profit_factor)}</td><td>{String(adverse.net_pnl_price)} / {String(adverse.profit_factor)}</td><td><code>{item.fingerprint.slice(0, 14)}</code></td></tr>; })}</tbody></table></div></section>
    {verification && <section className="panel result-panel variant-verification"><div className="panel-header"><div><h2>Sprint 15 acceptance verifier</h2><p>{verification.terminal_state} · {verification.fingerprint.slice(0, 16)}</p></div><span className={`capital-readiness ${isVariantAcceptanceReady(verification) ? "passed" : ""}`}>{verification.owner_acceptance_readiness}</span></div><div className="capital-checks">{Object.entries(verification.checks).map(([key, item]) => <article key={key}><span className={`validation-status ${item.status === "PASS" ? "passed" : "failed"}`}>{item.status}</span><div><strong>{labels[key] ?? key}</strong><small>{JSON.stringify(item.observed ?? "Recorded")}</small></div></article>)}</div><p className="warning-line">{verification.warning}</p></section>}
  </>;
}

export function VariantExplorer() {
  const [strategies, setStrategies] = useState<Strategy[]>([]); const [datasets, setDatasets] = useState<Dataset[]>([]); const [strategyId, setStrategyId] = useState(""); const [datasetId, setDatasetId] = useState("");
  const [stops, setStops] = useState("0.05, 0.10, 0.15"); const [targets, setTargets] = useState("0.05, 0.10, 0.15"); const [validation, setValidation] = useState<ContractValidation | null>(null);
  const [contracts, setContracts] = useState<Contract[]>([]); const [contract, setContract] = useState<Contract | null>(null); const [train, setTrain] = useState<TrainRun | null>(null); const [holdout, setHoldout] = useState<HoldoutRun | null>(null); const [verification, setVerification] = useState<VariantVerification | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const contractPayload = useMemo(() => ({ schema_version: 1, axes: { "stop_loss_rule.distance": axis(stops), "take_profit_rule.distance": axis(targets) }, maximum_combinations: 25, cost_scenarios: costScenarios, partition_policy: partitionPolicy, selection_policy: selectionPolicy }), [stops, targets]);
  async function act(task: () => Promise<void>) { setBusy(true); setMessage(""); try { await task(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(false); } }
  async function openContract(item: Contract) { setContract(item); setStrategyId(item.strategy_version_id); setDatasetId(item.dataset_id); setVerification(null); const trainBody = await read(await fetch(`/api/v1/variant-experiment-contracts/${item.id}/train-runs`, { cache: "no-store" })); const selectedTrain = (trainBody.train_runs ?? [])[0] ?? null; setTrain(selectedTrain); if (selectedTrain) { const holdoutBody = await read(await fetch(`/api/v1/variant-train-runs/${selectedTrain.id}/holdout-runs`, { cache: "no-store" })); setHoldout((holdoutBody.holdout_runs ?? [])[0] ?? null); } else setHoldout(null); try { const check = await read(await fetch(`/api/v1/variant-experiment-contracts/${item.id}/verification`, { cache: "no-store" })); setVerification(check); } catch { /* verifier is explicitly materialized */ } }
  useEffect(() => { void (async () => { try { const [s, d, c] = await Promise.all([fetch("/api/v1/strategy-versions", { cache: "no-store" }).then(read), fetch("/api/v1/datasets", { cache: "no-store" }).then(read), fetch("/api/v1/variant-experiment-contracts", { cache: "no-store" }).then(read)]); const eligible = (s.strategy_versions ?? []).filter((item: Strategy) => ["CONTRACT_VALID", "VALIDATED"].includes(item.status)); const data = (d.datasets ?? []).filter((item: Dataset) => item.symbol === "XAUUSD" && item.timeframes.some(asset => asset.timeframe === "M1")); const existing = c.variant_experiment_contracts ?? []; setStrategies(eligible); setDatasets(data); setStrategyId(existing[0]?.strategy_version_id ?? eligible[0]?.id ?? ""); setDatasetId(existing[0]?.dataset_id ?? data.find((item: Dataset) => item.evidence_grade !== false)?.id ?? data[0]?.id ?? ""); setContracts(existing); if (existing[0]) await openContract(existing[0]); } catch (error) { setMessage(error instanceof Error ? error.message : "Variant evidence could not be loaded"); } })(); }, []);
  const validate = () => act(async () => { const report = await post("/api/v1/variant-experiment-contracts/validate", { strategy_version_id: strategyId, dataset_id: datasetId, contract: contractPayload }); setValidation(report); setMessage(report.assessment.ready ? "Bounded experiment contract is ready." : report.assessment.issues.join(" ")); });
  const confirm = () => act(async () => { if (!validation?.assessment?.ready) throw Error("Validate a ready contract first."); const item = await post(`/api/v1/strategy-versions/${strategyId}/variant-experiment-contracts`, { dataset_id: datasetId, contract: contractPayload }) as Contract; setContracts(current => [item, ...current.filter(value => value.id !== item.id)]); await openContract(item); setMessage(item.reused ? "Identical experiment contract reused." : "Immutable experiment contract confirmed."); });
  const runTrain = () => act(async () => { if (!contract) throw Error("Choose a confirmed experiment."); const item = await post(`/api/v1/variant-experiment-contracts/${contract.id}/train-runs`) as TrainRun; setTrain(item); setHoldout(null); setVerification(null); setMessage(item.reused ? "Exact train evidence reused." : "Train matrix completed."); });
  const runHoldout = () => act(async () => { if (!train) throw Error("Run or open train evidence first."); const item = await post(`/api/v1/variant-train-runs/${train.id}/holdout-runs`) as HoldoutRun; setHoldout(item); setVerification(null); setMessage(item.reused ? "Exact holdout evidence and lock reused." : "Holdout selection locked."); });
  const verify = () => act(async () => { if (!contract) throw Error("Choose a confirmed experiment."); const item = await post(`/api/v1/variant-experiment-contracts/${contract.id}/verification`) as VariantVerification; setVerification(item); setMessage(isVariantAcceptanceReady(item) ? `Sprint 15 verifier PASSED${item.reused ? " · immutable artifact reused" : ""}.` : "Verifier found a blocking invariant."); });
  const confirmFinal = () => act(async () => { if (!holdout || holdout.selection.status !== "VARIANT_SELECTED") throw Error("Only VARIANT_SELECTED can open final-OOS."); const item = await post(`/api/v1/variant-selection-locks/${holdout.selection.id}/confirm-final-oos`, { acknowledgement: "CONFIRM_SELECTED_VARIANT_FINAL_OOS" }); setMessage(`Final gate completed: ${item.result.gate_decision}.`); if (contract) await openContract(contract); });
  return <main className="backtest-page"><header><div><Link className="back-link" href="/strategies">← Strategy Library</Link><h1>Bounded Variant Explorer</h1><p>Owner-controlled train → holdout → lock → confirmation → final-OOS evidence.</p></div><span className="mode-badge">HISTORICAL ONLY · FINAL-OOS LOCKED</span></header><section className="backtest-content">{message && <p className="notice">{message}</p>}
    <section className="variant-grid"><section className="panel backtest-config variant-panel"><p className="discovery-kicker">1 · BOUNDED CONTRACT</p><h2>Declare explicit SL / TP axes</h2><label className="deploy-label">Baseline StrategyVersion<select value={strategyId} onChange={event => { setStrategyId(event.target.value); setValidation(null); }}><option value="">Choose baseline</option>{strategies.map(item => <option key={item.id} value={item.id}>{item.name} · v{item.version} · {item.status}</option>)}</select></label><label className="deploy-label">XAUUSD M1 dataset<select value={datasetId} onChange={event => { setDatasetId(event.target.value); setValidation(null); }}><option value="">Choose dataset</option>{datasets.map(item => <option key={item.id} value={item.id}>{item.fingerprint.slice(0, 12)} · {item.timeframes.find(asset => asset.timeframe === "M1")?.row_count} bars</option>)}</select></label><label className="deploy-label">Stop distances (comma-separated)<input value={stops} onChange={event => { setStops(event.target.value); setValidation(null); }} /></label><label className="deploy-label">Target distances (comma-separated)<input value={targets} onChange={event => { setTargets(event.target.value); setValidation(null); }} /></label><p className="capital-snapshot">Declared combinations: <strong>{axis(stops).length * axis(targets).length} / 25 maximum</strong></p><div className="actions"><button className="secondary" disabled={busy || !strategyId || !datasetId} onClick={validate}>Validate contract</button><button className="run-button" disabled={busy || validation?.assessment?.ready !== true} onClick={confirm}>Confirm immutable contract</button></div>{validation && <div className={`factory-state ${validation.assessment.ready ? "ready" : "invalid"}`}><strong>{validation.assessment.status}</strong><span>{validation.assessment.issues.join(" ") || "All bounded contract checks passed."}</span></div>}</section>
      <section className="panel backtest-config variant-panel"><p className="discovery-kicker">2 · RECORDED EXPERIMENT</p><h2>Open exact lineage</h2><label className="deploy-label">Experiment contract<select value={contract?.id ?? ""} onChange={event => { const item = contracts.find(value => value.id === event.target.value); if (item) void act(() => openContract(item)); }}><option value="">Choose confirmed contract</option>{contracts.map(item => <option key={item.id} value={item.id}>{item.status} · {item.fingerprint.slice(0, 12)}</option>)}</select></label><div className="variant-contract-facts"><p><span>Contract</span><strong>{contract?.fingerprint.slice(0, 16) ?? "—"}</strong></p><p><span>Train run</span><strong>{train?.status ?? "NOT RUN"}</strong></p><p><span>Holdout lock</span><strong>{holdout?.selection.status ?? "NOT RUN"}</strong></p></div><div className="actions"><button className="secondary" disabled={busy || !contract} onClick={runTrain}>Run / reuse train</button><button className="run-button" disabled={busy || !train} onClick={runHoldout}>Run / reuse holdout + lock</button></div></section>
      <section className="panel backtest-info variant-panel"><p className="discovery-kicker">SAFETY BOUNDARY</p><h2>No optimizer claim</h2><p>Only two predeclared price-distance axes are explored. Train screens, holdout selects, and final-OOS stays untouched until an eligible lock receives explicit Owner confirmation.</p><p><strong>NO_ELIGIBLE_VARIANT is terminal evidence.</strong> It cannot create a revision and must not be replaced by the least-bad negative result.</p><p>`VALIDATED`, if ever earned, remains historical-only and never authorizes DEMO/LIVE, capital, Router, or a current trade decision.</p></section></section>
    {holdout && <VariantEvidence train={train} holdout={holdout} verification={verification} busy={busy} onConfirm={confirmFinal} onVerify={verify} />}
  </section></main>;
}
